import type { ConsolidatedHeroOptional } from "@repo/database";

export const mockHeroStats: ConsolidatedHeroOptional[] = [
	{
		profile: {
			id: 1,
			name: "Freya",
			url_name: "freya",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "60",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Gold Lane" }],
			roles: [{ icon: "/placeholder.svg", title: "Fighter" }],
			speciality: ["Damage", "Burst"],
			tagline: "Valkyrie Queen",
			tale: "A fierce warrior from the north",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 1,
			name: "Freya",
			url_name: "freya",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.341,
			ban_rate: 0.452,
			win_rate: 0.672,
		},
	},
	{
		profile: {
			id: 2,
			name: "Karina",
			url_name: "karina",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "75",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Jungle" }],
			roles: [{ icon: "/placeholder.svg", title: "Assassin" }],
			speciality: ["Burst", "Mobility"],
			tagline: "Shadow Blade",
			tale: "A deadly assassin",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 2,
			name: "Karina",
			url_name: "karina",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.283,
			ban_rate: 0.843,
			win_rate: 0.658,
		},
	},
	{
		profile: {
			id: 3,
			name: "Franco",
			url_name: "franco",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "45",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Roam" }],
			roles: [{ icon: "/placeholder.svg", title: "Tank" }],
			speciality: ["CC", "Support"],
			tagline: "The Hook Master",
			tale: "A tank with deadly hooks",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 3,
			name: "Franco",
			url_name: "franco",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.421,
			ban_rate: 0.684,
			win_rate: 0.643,
		},
	},
	{
		profile: {
			id: 4,
			name: "Vexana",
			url_name: "vexana",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "55",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Mid Lane" }],
			roles: [{ icon: "/placeholder.svg", title: "Mage" }],
			speciality: ["Burst", "CC"],
			tagline: "Necromancer",
			tale: "Queen of the undead",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 4,
			name: "Vexana",
			url_name: "vexana",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.12,
			ban_rate: 0.08,
			win_rate: 0.631,
		},
	},
	{
		profile: {
			id: 5,
			name: "Aamon",
			url_name: "aamon",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "80",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Jungle" }],
			roles: [{ icon: "/placeholder.svg", title: "Assassin" }],
			speciality: ["Burst", "Mobility"],
			tagline: "Duke of Shards",
			tale: "A skilled assassin",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 5,
			name: "Aamon",
			url_name: "aamon",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.18,
			ban_rate: 0.684,
			win_rate: 0.625,
		},
	},
	{
		profile: {
			id: 6,
			name: "Layla",
			url_name: "layla",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "30",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Gold Lane" }],
			roles: [{ icon: "/placeholder.svg", title: "Marksman" }],
			speciality: ["Damage", "Poke"],
			tagline: "Malefic Gunner",
			tale: "A marksman with long range",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 6,
			name: "Layla",
			url_name: "layla",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.18,
			ban_rate: 0.02,
			win_rate: 0.421,
		},
	},
	{
		profile: {
			id: 7,
			name: "Miya",
			url_name: "miya",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "35",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Gold Lane" }],
			roles: [{ icon: "/placeholder.svg", title: "Marksman" }],
			speciality: ["Damage", "Push"],
			tagline: "Moonlight Archer",
			tale: "An agile archer",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 7,
			name: "Miya",
			url_name: "miya",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.15,
			ban_rate: 0.01,
			win_rate: 0.418,
		},
	},
	{
		profile: {
			id: 8,
			name: "Fanny",
			url_name: "fanny",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "95",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Jungle" }],
			roles: [{ icon: "/placeholder.svg", title: "Assassin" }],
			speciality: ["Mobility", "Burst"],
			tagline: "Blade Dancer",
			tale: "The most mobile assassin",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 8,
			name: "Fanny",
			url_name: "fanny",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.24,
			ban_rate: 0.872,
			win_rate: 0.541,
		},
	},
	{
		profile: {
			id: 9,
			name: "Gusion",
			url_name: "gusion",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "85",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Jungle" }],
			roles: [{ icon: "/placeholder.svg", title: "Assassin" }],
			speciality: ["Burst", "Mobility"],
			tagline: "Holy Blade",
			tale: "A skilled magic assassin",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 9,
			name: "Gusion",
			url_name: "gusion",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.32,
			ban_rate: 0.621,
			win_rate: 0.497,
		},
	},
	{
		profile: {
			id: 10,
			name: "Ling",
			url_name: "ling",
			createdAt: Date.now(),
			updatedAt: Date.now(),
			images: {
				head: "/placeholder.svg",
				head_big: "/placeholder.svg",
				painting: "/placeholder.svg",
				smallmap: "/placeholder.svg",
				squarehead: "/placeholder.svg",
				squarehead_big: "/placeholder.svg",
			},
			difficulty: "90",
			skills: [],
			lanes: [{ icon: "/placeholder.svg", title: "Jungle" }],
			roles: [{ icon: "/placeholder.svg", title: "Assassin" }],
			speciality: ["Mobility", "Damage"],
			tagline: "Cyan Finch",
			tale: "The wall-walking assassin",
			relation: {
				compatible_with: [],
				strong_against: [],
				weak_against: [],
			},
			source_link: "",
		},
		meta: {
			id: 10,
			name: "Ling",
			url_name: "ling",
			rank: "glory",
			updatedAt: Date.now(),
			pick_rate: 0.19,
			ban_rate: 0.768,
			win_rate: 0.482,
		},
	},
];
